//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order:TMP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Order()
        {
            this.Table_DetailOder = new HashSet<Table_DetailOder>();
        }
    
        public int O_OrderID { get; set; }
        public string O_Email { get; set; }
        public string O_DateOder { get; set; }
        public Nullable<int> O_SatatusBay { get; set; }
        public Nullable<int> O_Total { get; set; }
        public byte[] O_IMGPAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetailOder> Table_DetailOder { get; set; }
        public virtual Table_StatusBay Table_StatusBay { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
