//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Screen()
        {
            this.Table_Chair = new HashSet<Table_Chair>();
        }
    
        public int S_ScreenID { get; set; }
        public Nullable<int> S_MovieID { get; set; }
        public Nullable<int> S_CinemaID { get; set; }
        public string S_DateSN { get; set; }
        public string S_TimeSN { get; set; }
        public Nullable<int> S_StatusSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Chair> Table_Chair { get; set; }
        public virtual Table_Cinema Table_Cinema { get; set; }
        public virtual Table_Movie Table_Movie { get; set; }
    }
}
