//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Movie:TMP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Movie()
        {
            this.Table_Screen = new HashSet<Table_Screen>();
        }
    
        public int M_MovieID { get; set; }
        public string M_NameMovie { get; set; }
        public string M_DateInMovie { get; set; }
        public string M_DateOutMovie { get; set; }
        public byte[] M_PicMovie { get; set; }
        public Nullable<int> M_MovieStatus { get; set; }
    
        public virtual Table_StatusMovie Table_StatusMovie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Screen> Table_Screen { get; set; }
    }
}
