//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMovies
    {
        public int S_StatusMovieID { get; set; }
        public string S_NameStatus { get; set; }
        public int M_MovieID { get; set; }
        public string M_NameMovie { get; set; }
        public string M_DateInMovie { get; set; }
        public string M_DateOutMovie { get; set; }
        public byte[] M_PicMovie { get; set; }
        public Nullable<int> M_MovieStatus { get; set; }
    }
}
