//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOders
    {
        public int O_OrderID { get; set; }
        public int D_DetailOderID { get; set; }
        public Nullable<int> D_Order { get; set; }
        public Nullable<int> D_hairID { get; set; }
        public string O_Email { get; set; }
        public string U_EmailID { get; set; }
        public string U_Password { get; set; }
        public string U_Name { get; set; }
        public string U_LastName { get; set; }
        public string U_Phone { get; set; }
        public Nullable<int> O_SatatusBay { get; set; }
        public string O_DateOder { get; set; }
        public Nullable<int> O_Total { get; set; }
        public byte[] O_IMGPAY { get; set; }
        public int C_ChairID { get; set; }
        public string C_NameChair { get; set; }
        public int S_ScreenID { get; set; }
        public Nullable<int> S_MovieID { get; set; }
        public Nullable<int> S_CinemaID { get; set; }
        public string S_DateSN { get; set; }
        public string S_TimeSN { get; set; }
        public int C_CinemaID { get; set; }
        public string C_Name { get; set; }
        public int M_MovieID { get; set; }
        public string M_NameMovie { get; set; }
        public byte[] M_PicMovie { get; set; }
        public int B_SatatusBayID { get; set; }
        public string B_Name { get; set; }
        public Nullable<int> C_ScreenID { get; set; }
        public Nullable<int> C_Price { get; set; }
    }
}
